import { Orbitron, Space_Grotesk } from "next/font/google";
import "./globals.css";
import ParticlesWrapper from "@/components/particlesBg/ParticlesWrapper";
import ScrollProgressBar from "@/components/shared/ScrollProgressBar";

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "MD Alfaz | Web Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${orbitron.variable} ${spaceGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#050A12]">
        <ParticlesWrapper />
        <ScrollProgressBar />
        {children}
      </body>
    </html>
  );
}
